# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [1]:
import itertools
elements = ["A","B","C"]
combinations = itertools.combinations(elements,2)
for combination in combinations:
  print(combination)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [2]:
elements = ["Python", "is" ,"fun"]
cycle= itertools.cycle(elements)
for i in range(10):
  print(next(cycle))

Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [3]:
import glob
print(glob.glob("*py"))

[]


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [6]:
from bs4 import BeautifulSoup
soup = BeautifulSoup('''<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>''', 'html.parser')
print(soup.p.string)

AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [8]:
import re
input_string = "AI is transforming the world"
output_string = re.sub(r'AI', "Artificial Intelligence", input_string)
print(output_string)

Artificial Intelligence is transforming the world


**CP6**: Create a numpy array of 10 zeros.

In [7]:
import numpy as np
numpy_array = np.zeros(10)
print(numpy_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [11]:
numpy_array = np.arange(10,50)
print(numpy_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [12]:
numpy_array = np.arange(0,9)
numpy_matrix = numpy_array.reshape(3,3)
print(numpy_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

In [14]:
print("Large amounts of data are required to improve their generization, to reduce bias and to learn robust feature representation")
print("Large data is a sufficient of data for which a model can learn about a specfic task")

Large amounts of data are required to improve their generization, to reduce bias and to learn robust feature representation
Large data is a sufficient of data for which a model can learn about a specfic task


**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

In [16]:
print("The first one is  Adverserial Attacks on AI Models in which a malicous attackers can distort or manipulate an input data to mislead a models predictions")
print("The second one is AI Powered Misinformation and Manipulation in which an AI is used to create and spread misinformation")
print("We can prevent this by using : fact checking, by building a robuse and secure models and so on")

The first one is  Adverserial Attacks on AI Models in which a malicous attackers can distort or manipulate an input data to mislead a models predictions
The second one is AI Powered Misinformation and Manipulation in which an AI is used to create and spread misinformation
We can prevent this by using : fact checking, by building a robuse and secure models and so on
